### ISSUE TITLE
Fitting in SwiftUI

### ISSUE THREAD

**Issue by RdeWilde** [cl3m/multiplatform-compose#2]
Would it be possible to fit Swift UI into the current implementation?
From what it seems, current components are fully based on UI Kit

Although Swift UI is only supported by the newer platforms, it seems very interesting to use: it is simple yet powerful. Would it be a match?

**Comment by cl3m** [comment]
Kotlin Native has access only to objective-c. [Swift modules are not yet supported](https://kotlinlang.org/docs/reference/native/objc_interop.html) thus SwiftUI is out of reach.
