### ISSUE TITLE
Jetpack Canvas Graphics API 

### ISSUE THREAD

**Issue by CarsonRedeye** [cl3m/multiplatform-compose#3]
Have you considered implementing the new Canvas API for iOS? It does seem like a big project but it would be a pretty amazing API. Multi-platform drawing with a modern declarative style! I guess it could be nice to wait for Swift interop to write it in the new similar Paths and Shapes API in SwiftUI.

**Comment by cl3m** [comment]
I've made a test and it will be possible with skiko and Compose Multiplatform by JetBrains to use the Compose canvas API on iOS. It is not released yet so you'll have to wait though. I'm closing the issue.
